[package]
name = "abar"
version = "0.2.0"
authors = ["Laura Powles <laura@laurapowles.com>"]
edition = "2018"

[dependencies]
clap = {version = "2.33", features = ["yaml"]}

# add dependencies here
chrono = "0.4"
