[package]
name = "abar-bin"
version = "0.2.0"
authors = ["Laura Powles <laura@laurapowles.com>"]
edition = "2018"

[[bin]]
name = "abar"
path = "src/main.rs"

[dependencies]
abar = {path = ".."}

# add dependencies here
chrono = "0.4"
